### ISSUE TITLE
Realizzare una web application basata sui dati relativi al Servizio Smaltimento Rifiuti

### ISSUE THREAD

**Issue by esterpantaleo** [teamdigitale/daf-data-science#19]
!**domande riportate in grassetto**!

## DATI DA UTILIZZARE
* Open data sul Servizio Smaltimento Rifiuti (FC05B) nel pac-sose
* metadata relativi a indicatori disponibili su [daf-dataset-doc FC05B](https://github.com/altroisi/daf-dataset-doc/blob/master/pac_sose/FC05B.md)
* metadata relativi a codice catastale comuni disponibili ai link [Metadati Enti 2010](http://docs.opencivitas.it/Metadati_Enti_xlsx.zip), [Metadati Enti 2013](http://docs.opencivitas.it/Metadati_Enti_2013_xlsx.zip)
* popolazione comuni 2010 e 2013 (ho scaricato i file da ISTAT: link diretto agli zip file del [2011](http://demo.istat.it/bil20111009/dati/comuni.zip) - **non ho trovato il 2010** e [2013](http://demo.istat.it/bil2013/dati/comuni.zip))

## VISUALIZZAZIONE 1
Estendere il grafico [Percentuale di raccolta differenziata nei comuni con più di 150000 abitanti: servizi vs spesa nel comune di Milano](http://www.opencivitas.it/sites/default/files/Allegati/Rifiuti_4.pdf) per renderlo interattivo su tutti i comuni con filtri per selezionare comuni con <150000 abitanti o > 150000 abitanti come accade in [questa visualizzazione](https://www.gapminder.org/tools/#_chart-type=bubbles) ma aggiungendo schede per ciascun comune.

asse x: efficienza delle spesa nell'anno A (LQP_COD_5 del file fabbisogni)
asse y: livello dei servizi erogati nell'anno A (LQP_COD_6)
raggio di ciascun punto: numero di abitanti

## NOTE PERSONALI RELATIVE ALLA VISUALIZZAZIONE
controllo dimensionalità dati

|   anno | LQP_COD_5    LQP_COD_6 | Metadata Enti |
|---|------------------------------|-|
|2010| 6702 comuni con 539 NaN| |
|2013|6699 comuni con 225 NaN| |

## ALTRE POSSIBILITA'
Utilizzando file topojson dei comuni (caso 1) e delle regioni (caso 2) relativi agli anni 2010 e 2013 e anche i dati relativi all raccolta differenziata **che credo siano disponibili nei file determinanti rifiuti o sono anche disponibili su ISPRA?** realizzare le seguenti visualizzazioni

1. [Smaltimento rifiuti: andamento della raccolta differenziata dal 2010 al 2013 nelle principali città italiane](http://www.opencivitas.it/sites/default/files/Allegati/Infografica%20rifiuti.pdf)

2. [Smaltimento Rifiuti nelle province del Veneto](http://www.opencivitas.it/elenco-infografiche/servizio-smaltimento-rifiuti-le-percentuali-di-raccolta-differenziata)

Oppure eventualmente utilizzare dati che non sono ora disponibili nel pac-sose:
* Dati nel questionario FC05U;
* [Determinanti servizio rifiuti](http://www.opencivitas.it/dataset/2013-comuni-determinanti-servizio-rifiuti).

## NOTE PERSONALI
Oltre che nel pac_sose i dati relativi al fabbisogno (ma anche le spese) sono disponibili sul sito Open Civitas (fonti MISE e ISPRA) ai link:
* [fabbisogni 2010-2013](http://www.opencivitas.it/dataset/2010-fc05b-comuni-funzioni-riguardanti-la-gestione-del-territorio-e-dellambiente-servizio) 
* [fabbisogni 2013-2015](http://www.opencivitas.it/dataset/2013-fc05b-comuni-funzioni-riguardanti-la-gestione-del-territorio-e-dellambiente-servizio)  

Online i metadati degli indicatori per il fabbisogno non sono corretti. 

Il sito riporta le seguenti keyword:

Fabbisogni standard, indicatori, livelli quantitativi delle prestazioni, variabili e pesi determinanti, Addetti totali ASIA,Comune litoraneo,Densita' (Numero di abitanti per kmq di Centri, Nuclei, Attivita' Produttive e Case Sparse),Distanza in Km Comune-Impianto (media pesata) - Ponderata con tonnellate,Livello delle locazioni immobiliari ad uso ufficio - Prezzo al mq,Numero di alunni che fruiscono del servizio di mensa nelle scuole d'infanzia, primarie e secondarie di primo grado (statali, comunali e private),Numero di famiglie e convivenze,Numero di immobili non residenziali,Numero di immobili residenziali,Numero di posti letto ospedalieri,Numero di unita' locali ASIA che svolgono attivita' di servizi di alloggio e di ristorazione,Presenze turistiche in alberghi e strutture complementari

e riporta i metadati relativi agli enti.

**Comment by fabiofumarola** [comment]
1. [Smaltimento Rifiuti Veneto](http://www.opencivitas.it/sites/default/files/Allegati/Rifiuti_focusVeneto.pdf) si puo' fare anche sulle altre regioni usando i dati disponibili?
2. idem per [Percentuale di raccolta differenziata nei comuni con più di 150000 abitanti: servizi vs spesa nel comune di Milano]()
3 idem per [Smaltimento rifiuti: andamento della raccolta differenziata dal 2010 al 2013 nelle principali città italiane]()

Sarebbe l'ideale rifare le stesse infografiche utilizzando superset, ma per ora va bene puntare al sodo ossia a cosa presentare.

**Comment by esterpantaleo** [comment]
pushed to https://github.com/esterpantaleo/daf-sose-rifiuti-fabbisogno
