### ISSUE TITLE
Clustering dei comuni

### ISSUE THREAD

**Issue by davideveronese** [teamdigitale/daf-data-science#2]
Come proposto da @CriMenghini, mi sembra interessante fare un clustering dei comuni basato sui fabbisogni e produrre una visualizzazione dei risultati. 
Credo sia importante far vedere come con lo strumento DAF si possano fare analisi basate su tecniche avanzate, diverse da quelle rese disponibili in Excel o SQL (per fare due esempi banali).

- [x] Preparare il dataset con le variabili di cluster
- [x] Provare 2/3 tecniche diverse ed esplorare i risultati (K-means, t-SNE, ...)
- [x] Produrre una visualizzazione ed aggiungere le etichette di cluster al dataset

**Comment by CriMenghini** [comment]
Sto preparando il dataset per avere i nomi dei comuni, la provincia, la regione e la zona invece che il codice catastale! Ci sto mettendo un po' perchè ovviamente diveserse fonti chiamano comuni in modo leggermente diverso! Ma sarà pronto a breve 👍
