### ISSUE TITLE
One Pager Dati Open Civitas

### ISSUE THREAD

**Issue by mariaclaudia** [teamdigitale/daf-data-science#24]
# Open Civitas
Questo portale contiene i dati relativi a costi e fabbisogni di comuni e province italiane. 
Il portale e’ stato creato come caso di studio per riorganizzare il modo in cui i fondi dei comuni sono distribuiti sul territorio italiano, per favorire una equa distribuzione dei fondi prelevati ai comuni e distribuiti in base ai fabbisogni.

## Pain
La spesa pubblica italiana e’ di 830 miliardi: circa 300 rappresentano il cuore dei servizi pubblici (scuola, sanita’ e forze di polizia) una sessantina di miliardi sono investimenti in conto capitale. La spesa sociale è quasi 340 miliardi e poi gli interessi sul debito [fonte sole 24 ora](http://www.ilsole24ore.com/art/notizie/2017-10-26/gutgeld-spesa-pubblica-italiana-e-830-miliardi-085627.shtml?uuid=AEhpDvvC). 
Con il blocco dei turnover e’ stato diminuito il numero di persone della P.A. 4%, mentre le p.a. locali hanno contribuito per il 17%. Tuttavia, rimane un problema aperto come:

1. ridurre le voci di costo cercando di non ridurre la qualita’ dei servizi offerti
2. non aumentare la pressione fiscale sui contribuenti.

Possibili soluzioni potrebbero voler dire riorganizzare alcune voci di costo come ad esempio quanto fatto per la sanita’ dove nel 2015 tre quarti degli acquisti erano fatti dai singoli ospedali mentre nel 2017 gli acquisti sono centralizzati. 
Un altro esempio e’ quello del comune di Roma dove e’ stato fatta la chiusura-accorpamento 
di 10 stazioni di polizia con la creazione di 5 nuove. Le nuove stazioni sono state aperte privilegiando le aree periferiche che hanno minori costi in termini di affitto e un bisogno oggettivo di controllo sul territorio.
Questo lo si può fare raccogliendo i dati, misurando e incrociando diverse sorgenti dati. 

## Solution
Integrazione e analisi dei dati di Open Civitas per mettere in evidenza pattern geo riferiti sui costi relativi a:
- entrate tributarie
- ufficio tecnico
- anagrafe
- polizia locale
- istruzione
- viabilità
- ambiente
- sociale

Opencivitas contiene dati sui costi sostenuti dai vari comuni per le macro voci sopra e degli indicatori sulla ripartizione dei fabbisogni. I dati sono rappresentati a livello di comune e interpolati a livello provinciale.

In questo modo potremo analizzare i dati avendo una connotazione geografica che permetta di scoprire dei pattern interessanti per la distribuzione delle voci di competenza dei servizi.
In particolare, i dati di open civitas saranno integrati con: [redditi su base comunale](http://www1.finanze.gov.it/finanze2/analisi_stat/index.php?search_class%5B0%5D=cCOMUNE&opendata=yes), posizione geografica dei comuni, [openbilanci.it](https://www.openbilanci.it/).
Si analizzeranno:
- anomalie geografiche
- anomalie tra costi e valori osservati in openbilanci
- disomogeneità tra voci di costo e fabbisogno su base spaziale e demografica. 

Esempi:
- Comuni con un alto investimento sul sociale ti aspetti che ci siano meno persone nella forbice (poveri e ricchi)
- comuni con una forte forbice tra fabbisogni e costi reali.

## Revisione

0.1 draft 10/01/2018 Maria Claudia Bodino
1.0 prima revisione 10/01/2018 Fabio Fumarola

**Comment by fabiofumarola** [comment]
spostato nel wiki
