### ISSUE TITLE
Arricchimento Dati aiuti Mise

### ISSUE THREAD

**Issue by fabiofumarola** [teamdigitale/daf-data-science#8]
Per ogni azienda aggiungere
1. indirizzo, citta', provincia ....
2. coordinate geografiche

**Comment by mariaclaudia** [comment]
@fabiana001 trovi il csv "MappingRagioneSocialeIvaCodFisc.csv" con i dati da mappare [qui](https://github.com/teamdigitale/daf-data-science/blob/master/MISE%20Aiuti/data/D_general/)
Per l'analisi a livello comunale sarà decisivo capire la percentuale di entry che si riesce a mappare.

**Comment by mariaclaudia** [comment]
Da un primo test risulta che circa il 10% delle entry viene risolto dal servizio della Commissione Europea e quindi abbiamo il comune relativo a chi ha ricevuto l'aiuto.

Volendo fare un'analisi su base comunale bisogna valutare se ci sono e quali sono altre strade possibili per recuperare il comune dalla ragione sociale.
